//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocketEshop.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocketEshop.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.png.
        /// </summary>
        public static string flag {
            get {
                return ResourceManager.GetString("flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Additions.
        /// </summary>
        public static string latest_additions {
            get {
                return ResourceManager.GetString("latest.additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for something specific?.
        /// </summary>
        public static string looking_for_something {
            get {
                return ResourceManager.GetString("looking.for.something", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your favorite games with just a click..
        /// </summary>
        public static string slide1a {
            get {
                return ResourceManager.GetString("slide1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying and downloading games is now easier than ever with &lt;b&gt;Rocket&lt;/b&gt;!.
        /// </summary>
        public static string slide1b {
            get {
                return ResourceManager.GetString("slide1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover new worlds..
        /// </summary>
        public static string slide2a {
            get {
                return ResourceManager.GetString("slide2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find any game you want with &lt;b&gt;Rocket&lt;/b&gt;, every latest addition..
        /// </summary>
        public static string slide2b {
            get {
                return ResourceManager.GetString("slide2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t waste any more time..
        /// </summary>
        public static string slide3a {
            get {
                return ResourceManager.GetString("slide3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save time and enjoy your browsing with our efficient search algorithms..
        /// </summary>
        public static string slide3b {
            get {
                return ResourceManager.GetString("slide3b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Rated.
        /// </summary>
        public static string top_rated {
            get {
                return ResourceManager.GetString("top.rated", resourceCulture);
            }
        }
    }
}
